### ISSUE TITLE
Event item - add to Iplicit Catalog

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1059]
Update the existing process - https://dev.app.spiff.status.im/process-models/comms-and-brand:event-management:event-execution:create-event so that the newly created Event is added to the x_Event catalogue in Iplicit

**Comment by calexh-sar** [comment]
@sashayar13 what does `x` represent in `x_Event catalogue`?

**Comment by calexh-sar** [comment]
@sashayar13 each event created in the SpiffWorkflow Create Event process will have a corresponding Iplicit custom catalogue, e.g., the `2025 All-Hands` event would have a `2025_All_Hands_Event` catalogue?

**Comment by sashayar13** [comment]
@calexh-sar This is how the Event catalogue looks like in the Iplicit 
<img width="1561" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/314d3973-504c-4c68-85b7-56cad06967cb">

So, when a new Event is created through Spiff, the Event Code and Event Name should be sent to the Iplicit

**Comment by calexh-sar** [comment]
@sashayar13 and @madhurrya the Create Events process has been updated to also add an event, edit the event name and delete an event in Iplicit.  There are currently no events in the Data Store or Iplicit.  The one scenario I don't think you will be able to test is adding the Event Catalog, which would occur when you add the first Event and the Event Catalog has not been created yet.  Since the current Event catalog cannot be deleted, this may only be done on prod if there is not an Event catalog there.

@sashayar13 we should discuss how you want to handle events whose event end date has passed.

**Comment by madhurrya** [comment]
@calexh-sar here if I set Catalog name as 'x_Event catalogue' and search for data should I see the events there? Currently it is giving an error.
![image](https://github.com/sartography/spiff-arena/assets/110527567/3eaca21f-d780-46a8-b95b-5ca486cc3e25)

**Comment by madhurrya** [comment]
@calexh-sar Please ignore the above question. Catalog name should be just 'x_Event', then I got the events correctly. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/6efe1e8b-0fd5-4b56-b0c0-bc213244af5f)

**Comment by madhurrya** [comment]
Tested by adding/editing/deleting events and they are reflected under x_Event data.
Need to test in the Iplicit system, if we have access to that.

@calexh-sar how do we generate the Event Code? Is is a random unique code?

**Comment by madhurrya** [comment]
@sashayar13 I am not clear about the above comment. Not sure what I have to there.

**Comment by sashayar13** [comment]
@madhurrya no worries, I did a quick test today. Everything looks good so far
