### ISSUE TITLE
Vendor data store - Vendor ID

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1148]
Implement a logic for generating the vendor ID in the data store:
- Vendor ID format is XYZnnn
- where XYZ are the first 3 letters from the Vendor name; if the Vendor name is composed of 2 words and the first word has only 2 letters than the XYZ will contain the 2 letters from the first word + the first letter from the second word ; if the Vendor name is composed of only 1 word and the word has only 2 letters than Z will be eliminated and the letter code will be reduced to the 2 letters from the name of the Vendor
- nnn is a number 001, that will be set by default for all Vendors
- the number changes and increases only when 2 Vendors have the same 3 letters XYZ : for example ABC001 and ABC002 OR in case the 3rd Vendor with ABC is registered than the code becomes ABC003

**Comment by calexh-sar** [comment]
@MarD0607 is the intent of this issue so the Vendor ID used in the Data Store is the same as the Vendor's ContactAccount Code used in Iplicit?  

If not, there is a concern about using this technique.  If two or more users are creating a Vendor at the same time, they could retrieve the same state during the process and both create the same Vendor ID.  To account for this, we created a script to call that guarantees a unique Vendor ID, which is:`vendor_id = create_unique_kkv_top_level_key("vendor_data_store", "V")`.   The Vendor IDs are not necessarily be sequential, but they are unique.

If so, the posting to Iplicit should be included in the process so if the next sequential number turns out to already have been added, the process can loop back and check again for the next number in the sequence.

**Comment by MarD0607** [comment]
@calexh-sar Yes, that is the intent. 
Regarding posting to Iplicit, this is the final step of the Vendor Review and Approval process. So that means the Vendor ID = ContactAccount Code , must be generated when running Vendor Review and Approval , not when running Register New Contact or Start Vendor Onboarding.
I have also added an extra item to the ticket, including data field IntRef in the Vendor data, where IntRef will be the BBHR API ID of the user which initiates the Start Vendor Onboarding.

**Comment by calexh-sar** [comment]
@MarD0607 I created the [Ids](https://dev.app.spiff.status.im/process-models/misc:service-tests:iplicit:ids) Process Model and updated Start Vendor Onboarding and Register a new contact Process Models to use it.  I cleared the Vendor Data Store and added two new examples with the new Vendor Id.

**Comment by MarD0607** [comment]
I moved:
