### ISSUE TITLE
Collapsed sub process - arrow missing

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1154]
Some times the blue color arrow goes missing for Collapsed sub process

![Image](https://github.com/sartography/spiff-arena/assets/110527567/768383b3-08ee-4e6f-9470-87951942672a)

In the created instance also it is missing and no way to go inside.

https://dev.app.spiff.status.im/i/7003

After saving and reopening it seems to appear again.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/4219337e-cfd2-4c27-b911-6255fd4b4b31)

**Comment by jasquat** [comment]
@madhurrya when this happens, have you tried looking for errors in the console? I wonder if maybe an error occurred that is not allowing for the diagram to operate properly.

**Comment by madhurrya** [comment]
No I didn't check. Will check when I notice this again.

**Comment by calexh-sar** [comment]
@madhurrya I believe that what you are seeing may be by design.  When you initially add a Collapsed Sub-Process (CSP) and have not added any elements in it yet, there is no blue arrow:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/ccc32e25-aba5-461a-9b48-1f3f4229bdc6)

I believe this is an indication that the CSP is empty.  If you click on it the blue arrow will appear:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/247bc613-15d0-4fe4-a4a1-e01e0bc6f160)

And if you click on it and go "inside" and add elements, the blue arrow will persist:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/85bc804c-8787-4e94-b11b-65e183ed3b46)

If this is the behavior you are seeing, I suggest that it is by design and no work is needed.  If not, please elaborate per KB's request.

**Comment by madhurrya** [comment]
@calexh-sar this was a random issue. This is is the model I have used. It already had content inside.
https://dev.app.spiff.status.im/editor/process-models/misc:qa:bpmn-model-testing:mi-sub-process-service-task-sequential-loop/files/UT_MI_Sub_Process_with_service_task_sequential_loop.bpmn

When I open it now it comes with the blue arrow automatically. But that day it didn't happen like that. As I can remember I have noticed this randomly in other models also in the past.

![image](https://github.com/sartography/spiff-arena/assets/110527567/20172d3c-1491-47d7-9256-f4ca101ba923)

**Comment by madhurrya** [comment]
This was a random issue and didn't notice recently. So closing it.
