### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task_spec' - when terminating cycletimer models

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1174]
When I try to to terminate an instance of these two models that has been running for about an hour it gives this error. 

https://dev.app.spiff.status.im/process-models/misc:qa:timer-tests:cycle-timer-30s
https://dev.app.spiff.status.im/process-models/misc:qa:timer-tests:repeating-timer-intermediate-catch-event-with-scipt-task

![Image](https://github.com/sartography/spiff-arena/assets/110527567/eb08ea8f-1086-4fd1-a930-ca01ac148e98)

Not sure whether this has connection to this issue, which is also related to the above models.
https://github.com/orgs/sartography/projects/3/views/8?pane=issue&itemId=49664419

**Comment by jasquat** [comment]
with cycle timers, one thing I noticed is that the child tasks seem to end with some type of internal timer.EndJoin spiff task. The issue is when we terminate a process instance, this task gets removed and so the "EndEvent" is left with an empty children array. This is bad since it needs to have the internal spiff task "End" as a child.

so before terminate it's like:
`EndEvent -> End -> EndJoin`

after terminate it's:
`EndEvent`

**Comment by madhurrya** [comment]
Noticed the same with a Boundary cycle timer also. https://test.app.spiff.status.im/process-models/misc:qa:timer-tests:boundary-cycle-timer-1-hour


![Image](https://github.com/sartography/spiff-arena/assets/110527567/4046a3b5-5d6f-491c-b4c1-da344d09e2e0)

**Comment by madhurrya** [comment]
Didn't notice this issue today. It seems to be fixed now.
