### ISSUE TITLE
Vendor data store - Deleting a vendor 

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1218]
We need a simple process that can be used to delete an entry from the Vendor data store.
The process should be available only for admins.

**Comment by calexh-sar** [comment]
@MarD0607 please check [this process model](https://dev.app.spiff.status.im/process-models/site-administration:data-store-maintenance:vendor) and let me know if this is what you have in mind.  I tested it once by deleting the `StickerMule US` vendor that was causing the error due to not having any `contact` data.

I have not done anything regarding permissions yet, we should perhaps consult with @sashayar13 and see if she agrees with the location of this data model and whether should would like to do the same for deleting Events.

**Comment by MarD0607** [comment]
The process works fine, thank you.
For now I only need it while running tests in case any data needs to be deleted.
