### ISSUE TITLE
Hamburger menu issue

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1253]
In dev.app when the menu is accessed through the hamburger menu, it is not closed after clicking on an item. The page seems to navigate to the selected page underneath. 
Earlier it closed upon selection. Now it stays like this.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/0f43527d-19d0-4c31-8fa4-2b9e7cdffff2)

**Comment by burnettk** [comment]
we noticed and thought about this, and actually fixed a cypress test by manually closing the menu after selection, but on second thought, you're right, it would probably be better to collapse it automatically, since the user is trying to navigate somewhere and see the full page where they are going to, so 80% of the time, they are going to immediately want to close the nav. i have a fix in progress.

**Comment by madhurrya** [comment]
This is fixed now.

**Comment by madhurrya** [comment]
Fixed in the Prod release on April 2nd
