### ISSUE TITLE
Support with multi instance synch processes

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1266]
Support in configuring the multi instance expanded process to run in different synch processes with Iplicit
For example:
https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:metadata-synch:bbhr-synch-with-vendor-md
https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:metadata-synch:vendor-data-store-synch-iplicit-data

**Comment by calexh-sar** [comment]
@MarD0607 this ticket should be prioritized by placing it in the priority order Status wants it worked on, not by assigning a sprint.  We will assign the sprint based on resource availability and priority order.

**Comment by calexh-sar** [comment]
@MarD0607 do you have specifics about the support you need?

**Comment by calexh-sar** [comment]
I did a cursory review of the process and it looks like the format of the post data and using codes instead of ids might be the issue.  Your post data looked like this:
`"iplicit_post_data": {
  "code": "GHJ001",
  "intRef": "277",
  "supplier": {
    "ext": {
      "ETH": "5%",
      "SNT": null,
      "Crypto": "1234567899",
      "BambooHRReference": "9992"
    },
    "contactGroupSupplierId": "CC"
  },
  "payTermId": "30",
  "description": "Gorilla Hyunday Johnny Test Ltd",
  "paymentMethodId": "BC",
  "defaultBankDetails": {
    "bic": "UGBIROBUXXX",
    "iban": "RO42BTRLRONCRT0555052301",
    "accountNo": null
  }
}`
and I think it should like something like this:
`"iplicit_post_data": {
  "description": "Gorilla Hyunday Johnny Test Ltd",
  "code": "GHJ001",
  "intRef": "277",
  "supplier": {
    "contactGroupSupplierId": "fb215a63-f625-44d2-8258-fcbd156e3390",
    "paymentMethodId": "1d9477d9-0f6d-489d-bf66-40490b42ceb3",
    "payTermId": "5f66776b-8156-4ffc-86bd-32658fd8004e",
    "ext": {
      "ETH": "5%",
      "SNT": null,
      "Crypto": "1234567899",
      "BambooHRReference": "9992"
    }
  },
  "bankDetails": [
    {
      "iban": "RO42BTRLRONCRT0555052301",
      "accountNo": null,
      "bic": "UGBIROBUXXX"
    }
  ]
}`

Not sure how far you want me to go with this, will wait to hear if you need anything else.

**Comment by MarD0607** [comment]
I will close this ticket since it is related to multi instance and @calexh-sar cleared up everything for me
