### ISSUE TITLE
Random page refreshes

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1289]
Recently we have been noticing some random page refreshing. For both admin and normal user.

**Comment by burnettk** [comment]
could be expired-token related.

**Comment by madhurrya** [comment]
I think I have noticed it in Process instance show page and home page. Mostly when I come from another window or a tab and click that tab it refreshes randomly.  (In the past also I have noticed such refreshes when I run cypress tests in parallel using the same user. But this time it seems it happens even when I am not running any cypress tests and just working with that user in one browser).
@dinithihj if you have more details please share.

**Comment by jasquat** [comment]
@madhurrya are you using chrome? and when you click on the tab what is the icon in the top left? I know chrome sometimes shuts down tabs if they aren't used in awhile and will refresh when you select it again.

**Comment by madhurrya** [comment]
I have noticed this in Edge also. And both me and Dinithi have been noticing this may be after the last deployment I think.
Can't remember about the icon. I really haven't paid much attention to this. Will check that next time.

**Comment by madhurrya** [comment]
I am noticing the page refreshes time to time. 
Few days ago Harmeet mentioned that he lost all the data he entered in a form due to a refresh.

**Comment by jasquat** [comment]
@madhurrya did you notice if there's a special icon on the tab when that does happen? Does it refresh just when you navigate to a tab or do you have to click on something (not including the home page since it auto-refreshes and I would like to keep it out of this discussion)?

For harmeet's thing, was it a form in a user task? That should have saved draft data if so.

**Comment by tcoz** [comment]
I dove into this a little bit, here's something I saw:

When you interact with a form, it preserves the in-progress state (so data the user has not submitted) via an authorized API call. Depending on the complexity of the call, that can be a few calls (like if you're just entering a number), or hundreds of calls (it looks like it triggers on a 2000ms debounce or something). 

If one of those calls fails, the user will probably lose the form and get kicked out. 

It'd seem to point to how the app responds to an auth'd API call returning as unauth'd, which is likely a token expiration issue or some such.

**Comment by madhurrya** [comment]
@jasquat Didn't notice any special icon like that. I have noticed it mostly when I come to that tab from another tab/window.

Don't know much details about Harmeet's issue. This is what he said "I just experienced a refresh on PROD for Request Goods and Services. Lost all my data. I thought that we fixed this issue long time before"
But this was before the latest Prod release. So it has nothing to do with the recent changes.

We have added 2 other refresh issues in the past. Not sure whether his issue is related to the first one here.
1. https://www.notion.so/Submit-Details-form-reloads-the-same-form-Random-issue-ba2072e7c40a4decac660bc0a8e3d648?pvs=4
2. https://www.notion.so/Page-refresh-on-BO-SME-review-page-PP1-PP2-3b0334c641d5498ebb7c90c3ea2f74d4?pvs=4

**Comment by jasquat** [comment]
Number one I believe is an auth token refresh issue which should be fixed now.

Number two I'm not sure about.

If this is happening for pages that are NOT the home page and it only involves you navigating from and to tabs then I'm inclined to blame the browser. How long are you away from a tab before coming back to it?

**Comment by jasquat** [comment]
@tcoz yep that's how it works. There's a debounce to send draft data to the backend every 500 ms. If there is an auth issue, it would fail and could possibly force the page to refresh. Most of that should be fixed now though since the backend should be using the refresh token to seamless update tokens and not force a refresh.

The requirement was not to lose form data so we went the route of adding it to the database. We could potentially switch to browser caching instead. I'm not sure if there's a requirement to keep data across devices.

**Comment by jasquat** [comment]
Oh wait, I just noticed that when navigating to and from tabs it makes permission-check requests. I'm not sure why it is doing that but that's something to look into.

**Comment by tcoz** [comment]
This is expected TanStack Query (formerly React Query) behavior; hooks and components (and their state) are sensitive to rendering cycles (by design). When the page encounters an event that could affect the DOM (a focus, route load, etc.) the state/cache framework does its thing; if it determines the data could be stale, it'll allow the call again (otherwise it returns it from the cache for the render, which is much faster). 

We can control whatever events are responded to (e.g. a mount) and when this happens (intervals), right now it's the defaults (which is pretty much the way you want to go 90% of the time).

**Comment by burnettk** [comment]
when i navigate between two tabs (Messages and Data Stores, http://localhost:7001/messages and http://localhost:7001/data-stores) over and over again, i do not see a permissions-check call in the network tab on every "new page." this is consistent for me on chrome and firefox. caching is doing what i would expect.

when jason does the same thing (also locally on main and in multiple browsers), he sees a permissions-check request every time he clicks on a nav item and switches pages.

**Comment by tcoz** [comment]
I haven't heard anything on this for a while, if it persists please assign to your new UI dev.

**Comment by madhurrya** [comment]
Closing this for now until we notice this again
