### ISSUE TITLE
Backend Not Working

### ISSUE THREAD

**Issue by abhishekdatacube** [sartography/spiff-arena#1321]
$ ./bin/run_server_locally

The currently activated Python version 3.12.0 is not supported by the project (>=3.10,<3.12).
Trying to find and use a compatible version. 
Using python3.11 (3.11.5)
Traceback (most recent call last):
  File "spiff-arena/spiffworkflow-backend/bin/save_all_bpmn.py", line 4, in <module>
    from spiffworkflow_backend import create_app
ModuleNotFoundError: No module named 'spiffworkflow_backend'
Exited with BAD EXIT CODE '1' in ./bin/run_server_locally script at line: 24.

**Comment by burnettk** [comment]
make sure you have latest main (`git checkout main && git pull`), since we support python 3.12 (the spiff-arena/.tool-versions says `python 3.12.1` and check out the [pyproject.toml](https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/pyproject.toml#L19)).
make sure you have run `poetry install`

be aware that there is also a docker compose file at the root of spiff-arena that you can use in docker if you want to avoid environmental issues, as well as a hosted version at https://spiffdemo.org/.

will close, and feel free to respond or re-open as appropriate.
