### ISSUE TITLE
User form issues

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1326]
https://www.notion.so/User-form-issues-c322566b708344e18db63f458ea99236?pvs=4

**Comment by jasquat** [comment]
this was due to commit 659112a3e47669a9ee32147eef4dbb10b23faf25 where we updated to update rjsf packages. this has been reverted and pushed.

The problem seems to have been that the updates to the select widget were not sufficient for the upgrade. We will have to debug it to find the proper solution.

**Comment by calexh-sar** [comment]
Closed per @sashayar13 instructions during ticket grooming.
