### ISSUE TITLE
MI missing completed task data

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1362]
These models are failing in dev.mod. But the same is working in dev.app.

1. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-parallel-user-task-loop-cardinality
https://dev.mod.spiff.status.im/i/36216

2. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-parallel-user-task-input-collection
https://dev.mod.spiff.status.im/i/36217

3. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-sequential-user-task-loop-cardinality
https://dev.mod.spiff.status.im/i/36218

4. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-sequential-user-task-input-collection
https://dev.mod.spiff.status.im/i/36219

5. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:ut-call-activity-with-mi-parallel-manual-task-input-collection
https://dev.mod.spiff.status.im/i/36221

6. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:ut-mi-sequential-call-activity-user-task-input-collection
https://dev.mod.spiff.status.im/i/36222

7. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:mi-sub-process-user-task-parallel-loop-cardinality
https://dev.mod.spiff.status.im/i/36223

8. https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:ut-mi-sub-process-expanded-user-task-sequential-loop-cardinality
https://dev.mod.spiff.status.im/i/36224

9. moved to #1512, since the fix, if any, will be different.

**Comment by madhurrya** [comment]
@burnettk @jasquat we'll have to fix these issues also in dev.mod. I am still seeing these issues.

**Comment by jasquat** [comment]
I think most of these models should be fixed with PR #1497.

I'm not sure about that last model though. How valid is it to put an end condition on a parallel multi-instance task? If all tasks are running in parallel how does it know to stop? I also can't understand why running without celery runs it consistently and with celery it's inconsistent how the data ends up. It looks like either way the backend is running all available multi-instance tasks at once in threads.

@essweine any insight into this? The model in question is https://dev.mod.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-parallel-loop-cardinality and some how without celery, the end task data only has 5 elements while with celery it normally has 10 but I have also seen 5, 2, 3, etc...

**Comment by essweine** [comment]
I would consider a completion condition valid here.  When any of the instance tasks completes, the output collection gets updated; then the last merged child's data is used to evaluate the completion condition; if the completion condition is met, any unfinished children are then cancelled.  Overall state is managed through the MI task.  I imagine that simultaneous updates of the MI task are overwriting others in a non-determinate way.

**Comment by jasquat** [comment]
PR #1497  has been merged to fix models 1-8. Number 9 will be monitored in #1497.

**Comment by madhurrya** [comment]
These issues are fixed now.
