### ISSUE TITLE
Upload expense processes - Legal name field value doesn't get set

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1391]
This ' Legal name' field should be prepopulated with the correct value. But after the latest code update it's empty.

New instance after the code update is missing the Legal Name - https://test.app.spiff.status.im/i/3471

![Image](https://github.com/sartography/spiff-arena/assets/110527567/beb72308-6a3c-464e-9a51-0d77ebf6d530)

Instance created before the code update shows the correct value -  https://test.app.spiff.status.im/i/3467

![Image](https://github.com/sartography/spiff-arena/assets/110527567/f08672e5-a8b0-4e09-a7de-5fb7031c6fba)

I looked a bit in to the above issue and noticed that In the new instance, the variable relevant to this field ( "core_contributor_legal") is available in this call activity task data, but it is missing in this gateway and after that. 
But for the old instance it's there in the gateway and after that also. That might be the reason that field is empty in the form. But not sure why that field goes missing after that call activity.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/ad4c718a-8d74-48d7-81a5-324f00b486e6)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/e9501f89-946f-43b1-81ea-c8705e142aa8)

These are 2 other instances from another Upload expense process.

Old instance which completed successfully.
https://test.app.spiff.status.im/i/2985

New instance where the legal name is missing now
https://test.app.spiff.status.im/i/3492

**Comment by jasquat** [comment]
@burnettk and I created this process model which helps demonstrate the issue: https://github.com/sartography/sample-process-models/tree/sample-models-1/misc/test-subproc-postscript-parallel-gateway

The process finishes but the hash key set in the post script of a subprocess (or call activity) does not make it to the gateway. It's like it's hash is completely overwritten by the hashes for the other tasks.

A couple notes:
* changing the ending parallel gateway to an exclusive gateway makes this work
* hash keys set in the pre-script or inside the subprocess work fine
* variables set in the post script also work fine - it's only new keys added to existing hashes that seem to fail

**Comment by madhurrya** [comment]
Managed to recreate the issue here based on Jason's comment.
https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-parallel-gateway-with-call-activities

Also added the above sub process example here
https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-parallel-gateway-with-subprocess

@jasquat in the third point you have mentioned -  "variables set in the post script also work fine - it's only new keys added to existing hashes that seem to fail". It seems variables are also going missing. Please check the 'iplicit_supplier_name' variable here. https://dev.app.spiff.status.im/i/5013
But saw that in your example the variable was working.

**Comment by jasquat** [comment]
Yeah any variable set BEFORE the parallel gateway has a chance of getting overwritten. `iplicit_supplier_name` was originally set in the "Set vars" script task so only one of the two tasks run in parallel will win.

**Comment by jasquat** [comment]
#1408 may fix a portion of this issue since it fixes data sharing across tasks in a parallel gateway so they will each get their own copy now rather than sharing the same object.

Do note that modifying a variable in a parallel task that was set in a previous task is not recommended. It is uncertain if that change will make its way to the final data. Instead only create NEW variables in a parallel task and then modify existing variables AFTER.

That would mean in @madhurrya's example, `iplicit_supplier_name` should only be created and set in `Get Supplier details` and not mentioned before that.

**Comment by jasquat** [comment]
@madhurrya @calexh-sar @sashayar13 

So the fix will be:
1. create a hotfix for test.app to fix the deepcopy issue - https://github.com/sartography/spiff-arena/pull/1409
2. update the process model so `exp_details["core_contributor_legal"]` is set AFTER all branches have been merged back together in https://test.app.spiff.status.im/editor/process-models/manage-finance:accounts-payable:process-expense-reports:capture-expense-data/files/capture-expense-details.bpmn

**Comment by sashayar13** [comment]
@jasquat, is this issue only when the parallel gateway is used for merging branches, or will it be the same for all other types of gateways (excluding exclusive)?
I think it'll be difficult to remember that we can't use post-script for certain cases.

**Comment by burnettk** [comment]
it's only an issue for parallel gateways.

in a situation where different branches happen in parallel, it's basically confusing for multiple branches to be modifying the same data. in this case, multiple branches are modifying the `exp_details` dictionary (that was created before the parallel branches started). that is the thing to avoid, if that makes sense.

**Comment by sashayar13** [comment]
But I think it's a standard practice where a process performs certain activities in parallel, which causes modifications of the same object. It can be confusing to avoid such things, also keeping in mind that this is a limitation only in certain cases.

Is there a way to return to the engine's previous state, when such scenarios worked fine?

**Comment by burnettk** [comment]
yes, that's right madhu, anything that runs branches in parallel, including inclusive, good point.

the previous state is unfortunately that it was working by accident, since a specific task on a specific branch happened to run last because the diagram was drawn in a particular way, and it happened to do what we wanted.

we are hoping that the change we made does return it to behaving the way it worked before for this process model.

if branch a sets `exp_details["hotvar"] = 1` and branch b sets `exp_details["hotvar"] = 2`, there is no way for the system to know which is desired, and in fact any two branches that do anything with `exp_details` are going to conflict, since the last branch that runs is going to overwrite that entire dictionary (this is the way it has always worked). running things in parallel when we need to depend on the data those branches generate is going to require a bit of extra thought for process architects, i think.

**Comment by sashayar13** [comment]
@burnettk @madhurrya when are you planning on releasing the code to prod - I'll need to update the process model there before the code change is shipped.

**Comment by madhurrya** [comment]
@sashayar13 I think we can do the code release around Monday or Tuesday, if no new issues are found. Will let you know exactly on Monday.
