### ISSUE TITLE
New UI plumbing and Dashboards Screen

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#1458]
Please see Figma Design here: https://www.figma.com/file/QtUtUWUusFSzt3Zxc62Vkz/SpiffPages?type=design&node-id=0-1&mode=design&t=dKyd5vpF1b4KAdt2-0

- Add a new route to the site - so we don't overwrite the current home page, make it top level 
- Most of the visible components implemented in some way.
- Data Hooks are optional (it may not return a list of real data yet) 
- We'll grab as much as we can from existing API endpoints.

**Comment by tcoz** [comment]
The current state running in the app looks like the pic below. It's all MUI/Figma based etc, with some customizations in the top-level theme based on requirements (primary purples etc.)

Will work in laying in some real data (user info, process lists) later today. 

Note that some of the responsiveness is wonky because this is a "UI in a UI", with some hackery to force it to 0,0 absolute positioning (as the "old" UI has other static assets on the top and to the left). 

![Screenshot 2024-04-30 at 11 35 19 AM](https://github.com/sartography/spiff-arena/assets/1213203/b5b78e55-0188-4e86-8aec-617d1a789ba0)

**Comment by tcoz** [comment]
This ticket is all set, moving on to other features.

**Comment by tcoz** [comment]
This ticket is all set, moving on to other features.
