### ISSUE TITLE
dev.mod - "The Data Output was not available in the subprocess output.." error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1563]
In dev.mod I am getting this error when running a PP1.

https://dev.mod.spiff.status.im/i/38872

![Image](https://github.com/sartography/spiff-arena/assets/110527567/6ada144b-e46a-4293-a0c9-46347898bdd0)

Due to this error can't complete any pp1/pp2 etc

Managed to recreate using this model.
https://dev.mod.spiff.status.im/process-models/misc:test:madhurya-testing:temp-group8:temp-model-8-10-call-activity-3

It works without any error in dev.app.
https://dev.app.spiff.status.im/i/1417

But it errors in dev.mod
https://dev.mod.spiff.status.im/i/38893

If I remove this call activity or changed the process it is calling, then it seems to be working fine.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/c02d22b8-9967-4f14-acf2-c301882cedc2)

**Comment by jasquat** [comment]
This seems to happen if the call activity doesn't set the variable `is_emp_out` it seems. If I do set that variable from within the process that the call activity calls, then the final task data contains the value for that instead of the one set in the current task. If the call activity isn't there then it uses the variable set in Script Task `Activity_1ev83sg`.

**Comment by madhurrya** [comment]
This issue seems to be fixed now
