### ISSUE TITLE
White screen - process instance search

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1576]
When you search a process instance by id  it shows a white screen, you need to force refresh the page 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/421964ea-fd0c-41a6-8a68-7fcc42e2e658)

**Comment by sashayar13** [comment]
notice white screen even with other admin manipulations with the process instance - View Call activity for example -

**Comment by jasquat** [comment]
I don't think you have to do a force refresh, it just takes a long time to load. We could add a loading icon there and load the page before all task info call has returned. The PR https://github.com/sartography/spiff-arena/pull/1562 should also help since it should load task info quicker.

**Comment by jasquat** [comment]
Yeah the time it takes to load will depend very much on how many tasks are associated with a process instance. The PR mentioned above keeps it from loading all of the tasks so it should load faster. So far I believe that PR is only on dev.app and not test.app.

I will look into displaying the page in pieces, so it can display things as they load instead of all or nothing.

**Comment by madhurrya** [comment]
Is this issue https://github.com/sartography/spiff-arena/issues/1615 related to the above fix?

**Comment by madhurrya** [comment]
@sashayar13 do you still notice this issue in test.app? May be you noticed this while things were very slow in test.app due to the waku issue last week. Do you think that's the case?

**Comment by burnettk** [comment]
Yes, #1615 is the new loading screen introduced to fix this.

**Comment by sashayar13** [comment]
@madhurrya I didn't notice this recently.

**Comment by madhurrya** [comment]
Yesterday noticed some white screens in test.app for some time. Not sure whether it was due to a network issue. As Sasha and Marius didn't notice anything like that at that time.

![image](https://github.com/sartography/spiff-arena/assets/110527567/ddd4ee0a-6a76-4796-8a68-d4e700509803)

![image](https://github.com/sartography/spiff-arena/assets/110527567/f7292521-4d6b-4702-a2dc-3096b9936adc)

**Comment by madhurrya** [comment]
Didn't notice this issue today in test.app
May be it happened with the servers issues/network issues

**Comment by madhurrya** [comment]
Released to Prod on June 18th. Version 19/20.
