### ISSUE TITLE
Some models looking for the schema json under a different model

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1684]
When I run this model https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-escalation-end-event it's looking for the schema file under a different model.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/b00e9538-e002-4fa6-8f3e-14ecf4a518d3)

Same happens for this also https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-error-boundary-event

![Image](https://github.com/sartography/spiff-arena/assets/110527567/d19f3452-2264-45bc-a4e7-782e178a3ae9)

**Comment by madhurrya** [comment]
I pushed the above 2 models to test.app and it works fine there.

**Comment by jasquat** [comment]
Originally stated in slack:

 it looks like that process id - escalation_end_event - is used in 2 different models: https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-escalation-end-event AND https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-call-activity-with-escalation-boundary-event.
the second model is not on test.app which is why it works there.
so apparently this code requires that process id to be used in only 1 bpmn diagram which used to be the assumption across the whole app. i don't know if it still is.
so since this process id gets used in multiple places, the code gets confused where the json file is supposed to come from since it uses the process id

**Comment by madhurrya** [comment]
It works after I changed the Id.
I think this will not be an issue in the future with this update as the user will not be able to create 2 models with the same id https://github.com/sartography/spiff-arena/pull/1581
