### ISSUE TITLE
Calculate median time to complete a process model

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#1719]
It was suggested that adding the typical amount of time spent on completing an instance of process model would be highly informative to those about to start the process.  It helps establish expectations early on, should be fairly easy to calculate, and would add a small piece of useful information to the process model tiles in the UI.

**Comment by harmeet-status** [comment]
It would make sense to have Superset data used here, as this type of information is already calculate in our data warehouse. @joseAnaya28 how do you think is the best way for Spiff to get access to this data?

**Comment by harmeet-status** [comment]
@danfunk I wasn't part of this discussion, where exactly were we thinking of showing this data? I ask since we also have the option of embedding superset reports in Spiff however if you are after just the data so you can incorporate it into some new UI element, will require a slightly different solution.

**Comment by JoseAnaya28** [comment]
@harmeet-status yes, we are already calculating this in one of the reports. 

We have a intermediate database that is acting as the interface between a user and the data warehouse. We can have Spiff access the data through there if needed.
