### ISSUE TITLE
'View process instance at the time when this task was active' feature is not working

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1964]
When I try to 'View process instance at the time when this task was active.' that activity becomes white, not yellow and I don't have a way to reset it as nothing happens when I click on it.

![Image](https://github.com/user-attachments/assets/e6002947-1dd6-495f-a960-51a9cc3e2d44)

I tried to 'View process instance at the time when this task was active.'  at the Manual Task 1. This is how it looks now.

Model : https://sample.spiffcrm.com/process-models/misc:qa:madhu-testing:call-activity-test-3

![Image](https://github.com/user-attachments/assets/7563d557-bdd0-4ace-a14e-fc7901327307)

'

**Comment by jasquat** [comment]
@madhurrya what process instance is in that screen shot? I was not able to replicate during a quick attempt.

**Comment by madhurrya** [comment]
@jasquat please try with this. https://sample.spiffcrm.com/i/1271
But this is not specific to a model or a instance. I have noticed this many times during my recent testing in different models/instances.

![image](https://github.com/user-attachments/assets/3adb4557-9033-4c9d-9d60-d9bcc4508cb2)

**Comment by burnettk** [comment]
@madhurrya we discovered that this is a floating point math problem that only affects sqlite. basically it compares end_in_seconds in the database vs end_in_seconds that came of the database. we ended up seeing a query like `select * from task where end_in_seconds  <= 1721672356.716494` fail even though the value in the db was purportedly `1721672356.71649`. float path math is stupid. we don't have these issues on other deployed environments because we're using `decimal(17, 6)` for storage of that column in mysql and similar in postgres. we happen to be using sqlite on the sample environment. we fail to replicate this issue on https://mysql.spiffcrm.com, which is the same as sample except for the database engine in use. please test this specific issue on mysql.spiffcrm.com and let's ignore it.

**Comment by madhurrya** [comment]
Yes this seems to be working fine in https://mysql.spiffcrm.com/.
So I'll close this ticket.
