### ISSUE TITLE
PI Migration - migration not allowed

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1973]
In this model, https://sample.spiffcrm.com/process-models/misc:qa:madhu-testing:call-activity-test-1 
I had this second level call activity model like this initially and I started the instance.
https://sample.spiffcrm.com/i/1290

![Image](https://github.com/user-attachments/assets/3e1a68d2-e6d7-4ea3-9520-ae08ce37a73a)

Now the instance is in this state

![Image](https://github.com/user-attachments/assets/703c4401-1c91-4771-91d0-4885043f3341)

Then I added this MM task to the above model like this and tried to migrate it.

![Image](https://github.com/user-attachments/assets/ca14eb31-e627-4696-850d-0e6c858a9e79)

It gives this message saying can't migrate. Why is that?

![Image](https://github.com/user-attachments/assets/15ba2662-d3ef-4b47-9c13-6cb3fc59e7cb)

**Comment by madhurrya** [comment]
Noticed a similar thing with this https://mysql.spiffcrm.com/i/20
Model : https://mysql.spiffcrm.com/process-models/misc:qa:madhu-testing:call-activity-test-1

I removed MMMM task and added FF and updated DD


![Image](https://github.com/user-attachments/assets/2c40146b-2f24-4e18-8b91-27956c6b8f86)



![Image](https://github.com/user-attachments/assets/f39f5a54-7be5-47f2-8987-eae9a3ca6ffb)

**Comment by jasquat** [comment]
I think we noticed this as well. If you have a CallActivity or Subprocess that is `STARTED` and you add a task after it on the same level, then you can't migrate it. I think this is because the subprocess task is changed and therefore spiff flags it.

Does that sound right @essweine?

**Comment by burnettk** [comment]
also, i kicked off an instance against http://localhost:7001/process-models/misc:qa:madhu-testing:call-activity-test-1 at version fe95203f locally, and then migrated it to 005c437f (newest). so that's strange, failed to repro.

**Comment by essweine** [comment]
Yes, it is because of the `STARTED` state, and the simplicity of the `can_migrate` function.  If only the outputs change, it probably would be safe to migrate it (or at least I can't think of any reason off the top of my head it wouldn't work).  On the other hand, it would not be safe for at least some other property changes (for example if it pointed to a different call activity).  So it would be possible to do finer grained checking and allow this, or leave it as-is.

**Comment by burnettk** [comment]
thank you. let's leave this alone for now. it seems totally conceivable that a user might care about this use case and want it to behave differently, but let's let it bubble up in that way, and glad to know that it's operating as designed.

**Comment by madhurrya** [comment]
@burnettk is this happening after a recent change? I don't remember it behaving like this earlier.
So we are not going to fix it?

**Comment by burnettk** [comment]
i don't believe it's a change. yeah, probably voting don't fix without a client asking for it.

**Comment by madhurrya** [comment]
@burnettk I am bit confused why we can't migrate it.
If I add a new task after the call activity when in this state, I can migrate it.
![image](https://github.com/user-attachments/assets/3577b32b-4990-41e1-b3f9-fc367646e9cb)

But if I add it when in this state, I can't migrate it.
![image](https://github.com/user-attachments/assets/6a84d033-9ee1-4b48-a83a-279cb211450f)

What is the reason for that?
And this seems to happen only when I add a task just after the call activity. If there's a task already after the call activity and if I add another one after that, I can migrate that.
Please check with this model https://sample.spiffcrm.com/process-models/misc:qa:bpmn-model-testing:unit-test-call-activity-with-manual-task

If the original models was like this

![image](https://github.com/user-attachments/assets/b332e8b7-927e-4f10-b6c0-f5a66c1a0992)


and if I added After 1, then I cant' migrate it.

![image](https://github.com/user-attachments/assets/c7ffebb8-0d83-413d-8e8b-89ab8d71a6f3)


But if the original model was like above (with the After 1) and if I added After 2, then I can migrate it. (while the call activity is active)

![image](https://github.com/user-attachments/assets/6eabbd72-9c0b-4310-94cd-845e0a31189b)

**Comment by essweine** [comment]
It is because the outputs of the call activity have changed (from the end event to the new task).  When you add the task later in the workflow, the outputs of the call activity remain constant.  The check that is performed disallows migration when any attribute of any task that is completed or running (`STARTED`), because by that time, it is necessary to (at best) consider individual attributes and (at worst) have to know the specifics of the changes and how they relate to the operation of the workflow itself.

This is not to say at least the first couldn't be done, but it adds complexity and we had made a decision to initially deal only with the simplest cases (only allow migrations when all changes were in the future) and this behavior is consistent with that.

**Comment by madhurrya** [comment]
@essweine just to make sure I understood it correctly, so the output changes only if we add a task immediately after the call activity/sub process, because it's adjoining the call activity/sub process. 
But if we add it after some other activities the output won't change as it's not joined to the call activity.
Is that correct?

**Comment by essweine** [comment]
Yes.
