### ISSUE TITLE
Script task : Can't import module

### ISSUE THREAD

**Issue by ManuelLevi** [sartography/spiff-arena#290]
I've tried to create a script task that uses the requests module to get online information.

When I try to run the process, I get the following error:

`ImportError:Import not allowed: requests. . ImportError:Import not allowed: requests.`

**Comment by jbirddog** [comment]
Granted this is not the direct answer you the issue, but traditionally speaking if you want to communicate with an external system you'd use a `ServiceTask`. In SpiffArena `ServiceTask`s are driven by the concept of a `Connector Proxy` which is some externally hosted system that conforms to a protocol that provides information about what communication channels are supported and executes those communication requests. Each connector proxy can have several commands. For this particular example it sounds like our `http/{Get,Post}` connectors may work. If not a custom connector could be written. For some examples we have:

1. [Connector proxy demo](https://github.com/sartography/connector-proxy-demo)
2. [Example http connector](https://github.com/sartography/connector-http)

These connectors can range from very generic (http/GetRequest) to hyper specific (xero/CreateInvoice) depending on the use cases.

**Comment by ManuelLevi** [comment]
1) My use-case: I'm using requests to actively check if an API is working correctly. This system is read-only, and I have no control over it. Another simple use-case is using a simple API to get a random number from https://www.random.org/clients/http/api/. 

2) On connectors: Do you have any documentation on how the connectors work? I've read what's available, but I wouldn't know where to start. It also seems a bit overkill to what I want to do.

3) If I was going to make changes to my own Fork of spiff-arena, where would I have to make changes so importing is allowed? I have tried to search this repo for "Import not allowed", but couldn't find any reference.

**Comment by jbirddog** [comment]
The documentation is a bit light in this area, but we do have a walk through for deploying a connector proxy as an aws lambda function - https://github.com/jbirddog/connector-proxy-lambda-demo/blob/main/deploy-integrate.md

If that route does not appeal to you then any other deployment would work. Your first use case seems to align well with the `http/GetRequest`.

If you want to continue to use a script task and import requests, @burnettk opened a [pr](https://github.com/sartography/spiff-arena/pull/297) to allow disabling the restricted python set up, which would allow you to import from within script tasks.

**Comment by burnettk** [comment]
@ManuelLevi yeah, definitely check out the hot doc @jbirddog linked and especially the section on integrating with SpiffArena for more details about how to interact with a connector proxy that is deployed. i think you have tried out the docker-compose.yml from https://www.spiffworkflow.org/posts/articles/get_started ? if so, there will already be a connector-proxy container running locally and you should be able to use a service task and configure it like this:

![image](https://github.com/sartography/spiff-arena/assets/18027/74cf577b-e170-4e85-a44b-5e74e15ae448)

when you run the process, it would get task data like this (note that the response variable, `respo`, gets populated with the response body of the http call:

![image](https://github.com/sartography/spiff-arena/assets/18027/8a2ba000-bea4-431d-a10f-20b0bd05b62d)

I'm going to go ahead and close this issue, but feel free to re-open it or otherwise get in touch with any additional questions. 👍

**Comment by burnettk** [comment]
@ManuelLevi awesome, did you end with using the service task / connector or the unrestricted python script environment?
