### ISSUE TITLE
Frontend doesn't always load completely

### ISSUE THREAD

**Issue by ManuelLevi** [sartography/spiff-arena#292]
Just after I run `docker-compose up`, I can open `127.0.0.1:8001` and log in into the frontend.

## When fully loaded, the menu has 5 buttons:
* Home
* Processes
* Process Instance
* Messages
* Configuration

If you're "home", you'll see three tabs and sections in each of them:
*In progress:* Tasks for my open instances, Tasks waiting for me, Tasks waiting for group: admin
*Completed:* My completed instances, With tasks completed by me, With tasks completed by group: admin
*Start New:* "Processes I can start"

## Not fully loaded

However, after some time has passed, if I try to open the frontend again, instead of seeing everything I see an incomplete menu:
* Home
* Processes
* Process Instances

And the tabs "In Progress", "Completed", "Start New +" have no content for them.

## Possible problem? 

Maybe I'm being logged out after a certain period? But if I am, I wasn't forwarded to a login page, or informed about not being logged in.

## Reproducing

I haven't found how to reproduce this yet. I'm guessing it happens when the backend fails so the frontend can't load the information anymore. 
I'll try to update this issue if it happens again.

**Comment by burnettk** [comment]
Yes, it sounds like frontend couldn't talk to backend. New images have been pushed that I think may resolve the issue you're seeing. One thing we had noticed is that the backend would deadlock when it received enough concurrent requests to exhaust the available worker processes (since it is using built-in openid, each request would need to talk to backend itself). That issue is resolved now, so if you run this in the directory where you downloaded the docker-compose.yml file, I suspect you may have a better time:

```
docker compose pull
docker compose down
docker compose up -d
```

Feel free to let us know if this recurs!
