### ISSUE TITLE
SQLite3 concurrency error when Arena is open in two tabs in an web browser

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#475]
When Arena is open in two tabs in a web browser and I do the edit and save on one, and 
then start the diagram on the other : 

**I got an error message in the diagram tab when going back to it after a start.**

```
OperationalError (sqlite3.OperationalError) database is locked
[SQL: UPDATE active_user SET last_seen_in_seconds=? WHERE active_user.id = ?]
[parameters: (1694010821, 11)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

 **It seems there is a concurrency problem in the backend with sqlite3.**

_I had the same problem in my own project and didn't manage to use the concurrency support of Sqlite3 (it depends on Sqlite3 version and python binding). So I solved it with a worker in a thread sending SQL requests one at a time to Sqlite3, from a stack._

**Comment by danfunk** [comment]
We discussed this as a team today.  We will create a separate ticket to address stale data in the active users table which may help reduce this issue.   We'll leave this ticket open since it's possible someone will encounter it, but it is unlikely we will ever be able to pick up this issue.  Please feel free to respond if you have any concerns or additional thoughts.

**Comment by madhurrya** [comment]
I couldn't recreate this issue. This might have been fixed with some other bug fixes. So closing this.
