### ISSUE TITLE
Dependency downloads have conflicting versions, missing dependencies, or deprecated dependencies.

### ISSUE THREAD

**Issue by DaytoyW** [sartography/spiff-arena#502]
Recently I've been trying to use spiff-arena with spiffworkflow build, the whole operation is carried out on ubuntu, where my nodejs and npm versions are v18.17.1 and 10.1.0 respectively, and did not choose to docker with the use of. Here the problem is mainly in the spiffworkflow-frontend run installation, in the execution of the installation of npm install some problems about the dependencies, first of all, there are some dependencies version conflict problem, according to the prompts to modify the re-execution of the npm install, and then the following screenshot suggests that many dependencies have been abandoned and need to be replaced and so on. Then the following screenshot shows that many of the dependencies have been deprecated and need to be replaced, and so on.
<img width="658" alt="be7f70b807a37d2a767c95a84a96347" src="https://github.com/sartography/spiff-arena/assets/113744843/0801019f-2dec-48ab-bce5-59a07465533b">

Then I tried npm start based on the above warning, and the src directory and the files in it were missing. This directory is supposed to be automatically downloaded to the appropriate directory during npm install, but I tried several times and found that it wasn't there, so I found the src directory under @microsoft on github and downloaded it locally and copied it over, then tried npm start again. Then I downloaded it and copied it locally, and tried npm start again, and it still couldn't find the file under src.
<img width="906" alt="98b3524a2fce89c5ac0602b8cb3412c" src="https://github.com/sartography/spiff-arena/assets/113744843/9978d182-8c6a-49d0-bc02-f2ddfc7dd5c0">

I've tried many times during the whole execution process, and most of the problems are dependency conflicts, missing and deprecated, so I'd like to ask what should I do next?

**Comment by burnettk** [comment]
You are seeing https://github.com/Azure/fetch-event-source/issues/18, I believe, in the second screenshot. I'm hoping they eventually fix it, but it isn't a fatal error. As for the wall of output during npm install, this is pretty typical, in my experience, for an npm project of any size. If there is a security issue, or if you have a pull request to resolve one of the issues, that would be welcome. If you are having a bunch of issues actually getting frontend to boot, which is not something I've heard a lot, I'd recommend docker, since this definitely works. Thank you for the report, and please keep the issues and PRs coming. 🙇
