### ISSUE TITLE
Consider an introspection based api as an alternative to data stores

### ISSUE THREAD

**Issue by jbirddog** [sartography/spiff-arena#539]
Mainly for discussion as we do #538 - depending on the use cases it could be feasible that an introspection based api can achieve the same end result in a safer/saner manner. If process b could query process a's task data/state (assuming permissions were good) then there is no need for process a to write to a mutable data store just so process b can read it. If process a and b both are running at the same time and need to share data back and forth as they run this might not work, but for the use case of process b just needs data from process a's end state, this could provide a powerful alternative.

**Comment by danfunk** [comment]
This would allow for cross dependencies between process models that are untraceable.  It would make process models harder to test.  It would make issues harder to debug.    What would appear to be an insignificant change in process model a could break process model b without warning and could be difficult to debug.   

While we have issues like this already, we should be working to reduce them.  Data inputs and data outputs would create clear boundaries around sub-processes.  And Data Stores that have a defined schema also create clear means of mocking out calls and dependencies for unit tests.  It's also clearly called out where dependencies exist. 

Debugging issues with a workflow in CR-Connect could, at times, take days to untangle.  Brain numbing, eye watering days, because the workflows are so interconnected.  Suffering through those debugging sessions is not something I want to do introduce.  Consider that we are marketing an option for 24/7 support - we should be doing everything within our power to make these workflows individually testable and executable with all dependencies between processes clearly defined.
