### ISSUE TITLE
Fix the data store modeling experience

### ISSUE THREAD

**Issue by jbirddog** [sartography/spiff-arena#549]
Currently you can drop a data store on to a diagram, and draw the arrows, but you need to go into the raw xml to properly wire things up. Ideally everything should be configurable from property panels.

**Comment by danfunk** [comment]
- [ ] - We should modify the Properties Panel to match the image below.
- [ ] - In addition to selecting the datastore, we should include the name of the variable that will be accessible in the task_data that can be used to reference the data store.
- [ ] - If the selected data store is a KKV data store then you should allow someone the option to provide the key so that only a single record is provided (otherwise all the values should be returned) 
- [ ] - If the selected data store is a TypeAhead data store, then it is WRITE ONLY - you can't just load 20,000 cities up as a dictionary.
- [ ] - If the selected data store is a Json data store, then you should be able to read from it and write it as a single object.
- [ ] - If the selected data store is a Json File Data Store, then it is defined in a file that is a part of the BPMN specification, and it is READ ONLY.  
![Image](https://github.com/sartography/spiff-arena/assets/515662/9fc112f4-f120-48a2-9edc-ad5d4c301dc3)

The KeyValue data store is backed by a database that might look similar to this - Each key-value data store can be accessed by name, and will have a primary key within it that will allow you to load a specific record.  Two possible uses of a KeyValue store

1. A table of values that share the same json schema - imagine a table containing all orders at a restaurant, all the contacts in a sales management system, all the animals at the zoo ...
2. A table containing drop-down list options - payment types, months of the year, types of specialty pizzas

Here the table that backs the key-value store.

![Image](https://github.com/sartography/spiff-arena/assets/515662/49c48a2c-eee8-476b-ac3d-0bad51bd7029)

**Comment by calexh-sar** [comment]
Work on this issue complete.  Subsequent updates to Data Stores will be in new issues
