### ISSUE TITLE
Add optional link to keycloak account from user profile top menu

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#708]
Any chance we could get the `https://[KEYCLOAK_DOMAIN]/realms/<REALM>/account/` link into the user navbar as Account (with About and Documentation links).

Perhaps we could implement this as an extension so people that wanted it on their deployed instance could get it. It makes a lot of sense when you are using keycloak.

jakub mentions that all should be derivable from openid config, and it is just the realm that differs across envs.

**Comment by calexh-sar** [comment]
@harmeet-status this issue needs to be prioritized

**Comment by harmeet-status** [comment]
@burnettk what is the benefit of this?

**Comment by burnettk** [comment]
jakub requested this, i believe because there are useful things that users can configure from their keycloak account page (password, 2-factor stuff, perhaps?).

**Comment by jakubgs** [comment]
Yes, it's a way for them to modify their password or 2FA.

**Comment by jasquat** [comment]
Implemented with #806 and view-keycloak-account extension.

**Comment by harmeet-status** [comment]
Closing this issue. Solved, as per above comment.

**Comment by jakubgs** [comment]
It appears to work without issues on https://dev.app.spiff.status.im/. Thank you.

**Comment by burnettk** [comment]
just opened PR for this on the process models repo. need to promote to test and prod.

**Comment by madhurrya** [comment]
@burnettk Is there anything we need to test in this ticket or can we close it? Is this already deployed to Prod or not yet? It's in Ready for release state but I am not sure about the state of that.

**Comment by madhurrya** [comment]
Noticed these when looking at this feature. Not sure whether we need to worry about any of them.

1. When I change the email and save, it shows the message 'your account has been updated'. But when I refresh and see the email hasn't been really updated. Is the email updating is not allowed?

![Image](https://github.com/sartography/spiff-arena/assets/110527567/80ff2127-cebb-468b-9f17-e8b7f8085744)

2. When I go to this link it says 'Page not found'.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/a6f3b9d8-0396-4855-8eea-7a9cd5e49607)

3. When I try to update a fisrtname/lastname in some of the test accounts we have, it gives this message. 'You can't update your username as it is read-only.'. Is that because these user's username in Keycloak is without the @status.im part (e.g user name xxcontributor instead of xxcontributor@status.im)? 
For the few users which had the user name with @status.im I was able to update the firstname/lastname.

Does the username has to be the same as the email?

**Comment by jakubgs** [comment]
Yes, the username is the same thing as email:

![image](https://github.com/sartography/spiff-arena/assets/2212681/e55b9bf5-cd4e-4476-a5ed-4406255649d6)

And editing username is disabled:

![image](https://github.com/sartography/spiff-arena/assets/2212681/8464ff04-7ec2-4907-9dfc-17c7efab8fee)

This is intentional as this is supposed to be managed by PeopleOps and in the future by BambooHR.

**Comment by madhurrya** [comment]
Harmeet said he added this to Prod. Can we close this now?
