### ISSUE TITLE
Ability to rollback process model to a previous version

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#756]
We need a way to do this in either Github or in Spiff.

**Comment by harmeet-status** [comment]
@burnettk what's the issue with rolling this back in Github? Can't that achieve the same purpose?

**Comment by burnettk** [comment]
Yeah, any change in github would be reflected in spiff right away with the webhooks.

**Comment by dinithihj** [comment]
@harmeet-status @burnettk Can you please let me how to test this ticket?

**Comment by harmeet-status** [comment]
@dinithihj if you can rollback a process model in Github, std GitHub functionality just google this. The process model should automatically be rolled back in Spiff.

**Comment by dinithihj** [comment]
I have googled this. It seems like there is no direct method to rollback from the GitHub web interface. However, there are few workaround methods that we can use to rollback process models to previous versions. I did not have permission to test below methods on status repos. but I tested them on one of my personal GitHub repo. 

**Using GitHub Desktop**
On GitHub Desktop if you right-click on the commit you want to rollback there will be an option called "Revert changes in commit"
![Screenshot 2024-03-08 110018](https://github.com/sartography/spiff-arena/assets/123297840/2349647e-b71e-47dc-9899-9c0de21ba81f)

When you select "Revert changes in commit," a new line appears as a revert action. 
![image](https://github.com/sartography/spiff-arena/assets/123297840/a10118dd-e899-4c4a-9218-4232a9e7ab06)

You can push this to repo to revert the selected commit. (I didn't have permission to do this on the status repo)
![image](https://github.com/sartography/spiff-arena/assets/123297840/f70a2d4d-756c-4371-9124-beb845419596)

**Reverting a PR**

If you've merged changes into the main branch using a pull request (PR), you can rollback by opening that PR again. There's an option to revert that particular PR, which creates another PR to revert those changes. I checked this on a test app with a PR I made before, but I couldn't see that option, probably because of permissions. The screenshot below is from my personal repository.

![image](https://github.com/sartography/spiff-arena/assets/123297840/88ca2b65-4269-4171-8990-935930c8bc46)

Please let me know if I need to check anything else related to this ticket.

**Comment by harmeet-status** [comment]
Once the PR was rolled back, was it reflected in Spiff? I.e. did the process model in Spiff go back to an older version?

**Comment by dinithihj** [comment]
@harmeet-status as I mentioned above I did not have permission to revert changes, to test whether it's reflected in Spiff.

**Comment by dinithihj** [comment]
Tested this with @harmeet-status with his permissions he was able to revert the PR that was created to test.app. Changes reflected on the Spiff and process model went back to the older version. 

Moving ticket to "Resolved"

**Comment by dinithihj** [comment]
Closing the ticket.
