### ISSUE TITLE
Hiding a process model

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#759]
How can we undeploy a process model in the case that we don't need it anymore?

**Comment by harmeet-status** [comment]
Short-term solution is to disable access to the process, if the team sees any issues.

**Comment by burnettk** [comment]
another already-available solution is to delete the process model in git.

**Comment by harmeet-status** [comment]
What would happen in the scenario that we delete the process model from Git, then we need to recover the environment, what would happen to the completed process instances?

**Comment by harmeet-status** [comment]
@burnettk is this a known bug? Perhaps we should create a ticket to fix this, as this can happen in prod and we should be able to see completed instances after disaster recovery.

**Comment by burnettk** [comment]
yeah, the system's delete function itself prevents you from deleting process models that are associated with process instances, but there may not be a lot we can do in the case when the user deletes directories from the git repo directly. we could potentially build monitoring of some sort to detect this sort of situation in order to notify someone, or perhaps we could build an interface that would allow you to inspect the system to see if this sort of anomaly was present. perhaps it could be part of the automated health check process model? this check does seem like something that could be of benefit even outside of status.

**Comment by calexh-sar** [comment]
Closing since we can already hide via permissions.  Will consider adding new issue for archiving process models.
