### ISSUE TITLE
Assist Marius with Vendor Onboarding process

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#790]

**Comment by MarD0607** [comment]
@calexh-sar 
1. When running Start Vendor Onboarding  ( https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:vendor-onboarding:start-vendor-onboarding ) I am experiencing similar issues in retrieving the data from the stored procedure and normalizing the response.
I have tried using the same normalizing script as a postscript in the service task instead of having it as a separate step in the process and have tried different options for the script to call the stored procedure (like with fetch_results and without fetch_results).
Please check the script and normalizing postscript, you can decide to keep the normalize step separate or delete it and keep the normalize script as postscript (similar to Register a New Contact process).
The user should be able to see the form and the process should build the enum_list.
2. Also in the case that there are no vendors with status New then the enum_list will be empty and this will generate an error as the process cannot continue with an empty enum_list, So we need to find a solution such as maybe add 1 item in the enum_list like None or No Vendor Available if there are no vendors with status New.
![image](https://github.com/sartography/spiff-arena/assets/137384667/7917f471-5881-451d-8285-877a854dc059)

**Comment by calexh-sar** [comment]
@MarD0607 I updated with a fix for #2.  Waiting for the outcome of the discussion in Discord on why the stored procedure is not added a new vendor or contact to understand what is needed for #1.

**Comment by MarD0607** [comment]
@calexh-sar **Register a New Contact**
I checked the Register a New Contact https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:vendor-onboarding:create-request-for-vendor-onboarding
and there are 2 fixes to be made:
1 - before adding the vendor contact data to the datastore, we need to check if there is any existing potentially similar data
And to do that we can check the domain name from the url_address added by the user in the form Vs domain names from existing data in the data store in vendor_web_url
Based on this check we should either add the data if the check returns false or not add the data if the check returns true (so there is an identical domain name). 
I we can do additional checks for example also the vendor name or the email address as well, that would be great.
2 - in the last step of the process Show the Vendor Data notification, I initially had instructions that would display a different message to the user if the check of the domain name returned True or False (instructions were made for the stored procedure).

**Comment by MarD0607** [comment]
@calexh-sar **Start Vendor Onboarding**
I checked Start Vendor Onboarding https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:vendor-onboarding:start-vendor-onboarding
and I have encountered just 2 problems:
1. - in Review Vendor Data, the user should see the data he entered in the form and by pressing the Edit button he should be redirected to the form to make changes if needed. However the from data is not displayed and Edit button does not trigger the edit action. 
2. In the end of the process as a Guest I see a Thank you message on the screen. Can I alter the message somewhere so it provides the guest user more info? I am thinking of something in the lines of "Thank you for submitting your company data. You will be soon notified of the result of the internal approval process. "
Also, an additional question, since I noticed the browser page remains opened until the user closes it. Is there any instance problem if the guest user does not close the browser page?

**Comment by calexh-sar** [comment]
@MarD0607 reagarding Start Vendor Onboarding #2, the Thank you message is the only option at this time, but if you want to add an issue to make the message configurable, we can estimate it so it can be prioritized.  And the process instance completes if the guest users leaves their browser page open.

Otherwise, I think I am done with this issue.  Please review and let me know if there is anything else you need or anything I missed.

**Comment by MarD0607** [comment]
I will close this task since the Start Vendor Onboarding is complete from a guest interaction perspective.
