### ISSUE TITLE
Github connector for task assignment, editing fields on task

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#820]
Bounty program requires us to be able to:

1. Assign task to a user (note that the user will need to be one of the users who is allowed to be assigned to issues in the repo in question)
2. Edit status of task (their rest api supports updating the state to either "open" or "closed". the rest is github projects which is editable using graphql)
3. Edit fields on task (some fields, like state above, are editable using their rest api, and github projects fields are editable using graphql)
4. Add comment to task (note that the comments will be from the user who oauthed)
5. The [Bounty process](https://cawemo.com/share/29b8873a-8332-42ca-bd75-864bddea8bc4) needs to be notified by GitHub that the PR for a specific issue assigned by the process has been approved. The pull_request_review webhook, when the event is "submitted", has a "review" object with a "state" property, and this property will be set to "approved" when the reviewer approves (see [spec](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=submitted#pull_request_review))
6. Confirmation when updating an issue field so that the appropriate action can be taken if the update is not successful.

See also https://github.com/sartography/spiff-arena/pull/434 and [app quickstart docs](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/quickstart). We have been using [this poor issue](https://github.com/sartography/spiff-arena/issues/936) to test integrations.

**Comment by harmeet-status** [comment]
@mrtrosen I thought this would be a good ticket for you to work on.

**Comment by harmeet-status** [comment]
@burnettk can you do some investigation and see if we need to build a specialised connector for this, or we can use HTTPS.

**Comment by burnettk** [comment]
@harmeet-status after a fairly thorough investigation, we have proven that we can accomplish this integration using the existing http connector.

**Comment by burnettk** [comment]
it's baked in to this estimate. we are currently using a test github app for the authentication mechanism that we showed in the demo. the current thinking is that we'd use spiffworkflow backend as the webhook receiver, and a process model would receive webhooks and do whatever it wanted with them. that part is the bulk of the remaining work on this ticket, and we'll probably hammer that after we address https://github.com/sartography/spiff-arena/issues/989.

**Comment by burnettk** [comment]
going to call this ready for qa. for #3, we can edit the "state" field of tasks (open/closed). we have a lot of github stuff working, and we will plug in the various functionality when we ready to create the actual bounty process.

**Comment by madhurrya** [comment]
@burnettk Is there a sample model which you already have which we can refer to test this?

**Comment by jasquat** [comment]
@madhurrya There are 2 models. One to test out some of the git functionality and one for the github webhook.

* github webhook: https://dev.app.spiff.status.im/process-models/site-administration:github-webhook
  * this requires some backend configuration to enable as well
  * currently this webhook also expects https://dev.app.spiff.status.im/process-models/misc:bounty:bounty to be there for the send message but not necessary to test the webhook portion
* example process model: https://github.com/sartography/enterprise-process-models/tree/main/examples/github-integrations
  * I don't know if this model is out on any environment at the moment

**Comment by madhurrya** [comment]
Thank you so much @jasquat

I uploaded the example process model here and it seems to work straightaway. https://dev.app.spiff.status.im/process-models/misc:qa:github-integration-test
One question. For the github webhook you have said 'this requires some backend configuration to enable as well'. Does that mean it is already enabled in dev.app, that's why the example worked?

**Comment by burnettk** [comment]
the github webhook part is separate from the github-integration-test stuff. we can talk about webhooks on a call if you want.

**Comment by harmeet-status** [comment]
@burnettk could you also test that a web hook using Github Actions can happen when some trigger on the issue.

**Comment by madhurrya** [comment]
I am testing using this model https://dev.app.spiff.status.im/process-models/misc:qa:github-integration-test with this test ticket https://github.com/sartography/spiff-arena/issues/1031

1. Tested assign user and it worked as expected. Tried assigning a test github user (whos is not in this repo) and that didn't get assigned. So I think it works as expected.
2. When I try the Update status option I get this error. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/7a4c9a26-5b8b-4eb7-993b-338a0dd6a110)
3. Commenting in the ticket also worked.
4. Clear assignees didn't work. 
For Clear assignee and Update status do we need to use separate api calls?
5. All the actions done through that process shows as done by KB. Is it because the github oAuth app is under KB's name? So in the Bounty process there will be a user, something like 'Bounty process' and all actions will be added from that account. Is that correct? 
![image](https://github.com/sartography/spiff-arena/assets/110527567/056ab3e0-7404-4564-bd00-819bd6e7f5d3)

**Comment by harmeet-status** [comment]
@madhurrya we should be able to assign anyone in the world to a ticket. Perhaps we need to look into the settings for this repo @burnettk

**Comment by harmeet-status** [comment]
@madhurrya can we also test misspelling a username and see if it throws an error.

**Comment by madhurrya** [comment]
@harmeet-status In the issue description you have said _"note that the user will need to be one of the users who is allowed to be assigned to issues in the repo in question"_. So based on that I thought we should be able to add only the users who are already added to the repo.

I tried with an invalid username, it doesn't get added but at the moment we don't show any error messages.

**Comment by burnettk** [comment]
addressing your points, madhu:

1. you cannot assign issues to just anyone. the quote "note that the user will need to be one of the users who is allowed to be assigned to issues in the repo in question" was actually from me, not harmeet, as i edited the description. note that https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users indicates that you can assign issues to users who have commented on the issue, so that might be a reasonable approach to consider.
2. that is because we didn't update the connector. we will do that after we complete #1032 
4. this wasn't actually a requirement. feel free to ignore.
5. yes, someone will oauth and the changes will be attributed to them, but with the app also given credit (it will show the user and the spiff icon together, like i maybe showed in the demo)

**Comment by harmeet-status** [comment]
> 1. you cannot assign issues to just anyone. the quote "note that the user will need to be one of the users who is allowed to be assigned to issues in the repo in question" was actually from me, not harmeet, as i edited the description. note that https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users indicates that you can assign issues to users who have commented on the issue, so that might be a reasonable approach to consider.

If we have to get the interested devs to comment on the ticket first, then it's a bit annoying workaround but doable. What are they going to comment on the ticket? "Hey I'd like to apply"? Sounds like a Facebook listing lol

Is there any other thing we can do, to avoid the above?

**Comment by burnettk** [comment]
if we are otherwise aware of them (via a certification process or something, i would guess?) and trust them, we could add them as contributors to the repos in question.

**Comment by madhurrya** [comment]
1. I commented using that outside user in that ticket and after that I was able to assign that user to the ticket, as KB mentioned.
![image](https://github.com/sartography/spiff-arena/assets/110527567/db78ba3c-ba87-4487-8b68-29deea5c8e1f)

2. Updating the state as closed/open also worked.
![image](https://github.com/sartography/spiff-arena/assets/110527567/541128f1-8318-4cac-9ca9-a34d3a5e2cb1)

3. Deleting a comment also worked

@harmeet-status is there anything else we need to test under this ticket?

**Comment by harmeet-status** [comment]
@madhurrya have we can close this once we can successfully change the status.

**Comment by madhurrya** [comment]
@harmeet-status As mentioned in the No. 2 above, I was able to set the status as closed and reopen. Is that what you meant?

**Comment by harmeet-status** [comment]
No that's not what I mean, I want the status on the board level: from "New Issue" --> "Backlog" --> "In Progress"

**Comment by harmeet-status** [comment]
What is left on this issue?

**Comment by burnettk** [comment]
in terms of what is left, we think the bounty process needs to fetch the DAI amount on a given issue, which is a graphql-related API. we don't have any obvious update-github-project related requirements for the bounty process at the moment, so we could ignore that in the context of this issue if that seems reasonable, as that one *might* be a little trickier.

**Comment by burnettk** [comment]
shoving this into ready for QA, @calexh-sar , please let us know if there's anything else.

**Comment by madhurrya** [comment]
@burnettk Harmeet has said in the comments above that we can close this ticket when we can successfully change the status.
I want the status on the board level: from "New Issue" --> "Backlog" --> "In Progress"

I guess it's not done yet. So I am moving this back.

**Comment by calexh-sar** [comment]
@madhurrya changing the Status was part of the GraphQL work @jbirddog did so we can understand how to use it.  I should be incorporating this into the Bounty process soon.

**Comment by calexh-sar** [comment]
Closing since all GitHub connector work complete in bounty process.
