### ISSUE TITLE
Guest URL Link works only in incognito mode

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#902]
Tests on accessing guest url has generated an error when the incognito mode is disabled.
![image](https://github.com/sartography/spiff-arena/assets/137384667/c0b3d0eb-db6e-4c25-9648-24a3dba4f74d)

**Comment by jasquat** [comment]
@MarD0607 can you give steps for how you got here? That url is to the process instance for-me show page. The guest user should never be taken there. If you are toggling between incognito mode and normal then it may be sending creds through sometimes and not others which may cause issues with the normal flow.

Instead of testing with incognito mode, I use 2 different browsers to test this where one is a normal signed in user and the other is not so it can complete the guest task.

**Comment by MarD0607** [comment]
@jasquat 
Yes, sry for the misunderstanding.
The process can be started by anyone with access to the dev environment. 
In the first user form the user needs to select to add a new vendor and enter the data required - company name, contact name, email, subject and message.
There is an additional user task that can be ignored since the text is optional.
After that the process checks if the data entered is not already in the DB, and then it generates the unique url and an access code. 2 separate emails are sent to the email address.
Until today I used to test it with different email accounts I had or created so all the tests were runned on the same machine.
The error appeared when I added the details of my colleagues and they tried to access the guest link.

**Comment by jasquat** [comment]
Thanks @MarD0607. I understand the issue now.

A signed in user cannot access guest tasks, they have to be signed out to do it. That is why it works in incognito mode since the cookie is probably not carried along in the requests. We also made an assumption that if a user is on the Task Show page - which is where the guest link will take you - when navigating away from it you would always want to go to the Process Instance For Me Show page. This is true in almost all cases except when a logged in user is attempting to access a guest task.

Some potential fixes:
* give notification that a logged in user is attempting to complete a guest task
* allow logged in users to complete guest tasks
   * this breaks the point of guest tasks though. if logged in users are expected to be able to complete the task then it may be better to use a lane or use lane owners to assign to a specific user
* attempt to be smarter of whether to go to the pi for me page or take the user to the home page

**Comment by MarD0607** [comment]
Thank you @jasquat 
That makes sense, when I was testing I was using different email accounts and different mail services, but when I ran the same test with someone else the email waa sent to a @status.im account.
Thanks for the support.

**Comment by calexh-sar** [comment]
@MarD0607 is this still an issue or can this issue be closed?

**Comment by MarD0607** [comment]
Yes it is still an issue.
But it is not a critical or urgent one.
The case when an user will be logged in as a status user and then be invited to onboard as a vendor will be rare. Usually the events will be in reverse order.

**Comment by MarD0607** [comment]
I will close this issue for now, will reopen it if the problem is reported by any of the CCs, but the use case will be rare and there is an immediate and simple workaround.
