### ISSUE TITLE
Breadcrumb navigation disappeared when deleting process group

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#910]
When I delete a process group the breadcrumb navigation got disappeared 

Example. I'm in Process Groups->Shared Resources->QA->Test1 and click on delete button to delete the process group Test1.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/7a47412f-25cc-4be8-8fba-d21a230bdc8f)

Breadcrumb navigation disappeared and only showed - Process Groups. 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/af640106-7d2b-4b3e-bfa9-feb4023dfe92)

Expected to show breadcrumb navigation for the parent group - Process Groups->Shared Resources->QA

**Comment by burnettk** [comment]
i think what's happening is it is taking you to the main process groups page (`/process-groups`) when you delete a process group (the same as if you click on "Processes" in the top nav). I guess we decided to do this because it's easy (rather than figuring out where to go, it just takes you to the main page). I'd probably vote don't change it, but if you understand the current behavior and still vote to change it to redirect to the parent group of the deleted group, I could get on board with that. What do you think?

**Comment by madhurrya** [comment]
Closing this as this is UI/UX related and will check this in the new UI
