### ISSUE TITLE
Permissions - Process with a Message-Start event

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#921]
Please configure the permissions in such a way that if a process is initiated with the "Catch Message Start Event" (and only with this event), it should not be displayed under the "Start New +" tab for users. Alternatively, the "Start" button should be disabled for such processes. 

To explain further, I have a scenario where there is a "Request Travel" process that initiates the "Upload Expense" process (through messages). The user should be able to open the instance of the "Upload Expense" evidence process that is created for them, but they should not be able to start the process from the "Start New+" tab

**Comment by burnettk** [comment]
i set up two process models, one with a message end event and one with a message start event, and configured permissions so that a start button was not displayed for the "message start" process: 
![image](https://github.com/sartography/spiff-arena/assets/18027/63767208-98b1-4b7f-8d87-5bb19435a12d)
the user who starts the first process is automatically set up as the process initiator of the other process, so this allows the user to complete human tasks on the second process.
i made a code change so that process instances will always be visible if they require your attention, but i'm not sure this would have affected status anyway. given that the concept has been proven as far as i understand it, i recommend setting up the process models as you describe and we can ensure that it works as you expect. this is how i set up permissions (note the absence of start permissions for the "message start" process model):
<img width="732" alt="image" src="https://github.com/sartography/spiff-arena/assets/18027/454ebf32-bda9-47e1-9385-42f5eeeb6ef8">

**Comment by dinithihj** [comment]
Tested and verified on dev.app (325-327) 

Created two process models, One with a Message Intermediate Throw event (921 Process A) and one with a Message Start event (921 Process B). 

Given Start permission to only model with Message Intermediate Throw event (921 Process A).
![image](https://github.com/sartography/spiff-arena/assets/123297840/b8cb6571-2405-45b5-9c45-0043b0afa47f)

When a user from the above group logs in and click on Start New+ button he can only see the process model with Message Intermediate Throw event (921 Process A)
![image](https://github.com/sartography/spiff-arena/assets/123297840/c2e12ea2-fc5b-4832-a4fc-e700a65f6e41)

When he starts 921 Process A, a new instance of 921 Process B was created and available on the Home page
![image](https://github.com/sartography/spiff-arena/assets/123297840/703ce7e5-ef67-4adb-8a0c-07694d936832)

He can complete the 921 Process B - Process model with the Message Start event
![image](https://github.com/sartography/spiff-arena/assets/123297840/2a80ae7a-5e6a-4ae1-a343-6ac0f808552b)

If this user navigates to the process group where these two models are located, Only Process A has the start button on it. And Process B does not show the start button
![image](https://github.com/sartography/spiff-arena/assets/123297840/8d11d034-440a-48a9-9331-e52c74a7945f)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
