### ISSUE TITLE
View files by opening them in a new tab, instead of having to download them

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#930]
Having to download files is quite annoying.

We should by default, open the file in a new tab OR design a pop-up which displays the file without having to leave your current browser tab.

**Comment by harmeet-status** [comment]
@burnettk do you think this is something that would be a good issue for @Kayvon-Martinez?

**Comment by burnettk** [comment]
If feasible, we might wait on this one until after the document management system work is complete, since that might change the mechanics of how this works fairly significantly.

Since we allow such a wide range of file types to be uploaded, doing something other than allowing the browser to handle them however it wants to handle them natively might be quite difficult. Imagine if the user uploads a Microsoft Word document. If we were to open a new tab and have the app render something, what would it render? There is a JavaScript library for everything, but if we play that game, it could end up increasing the size of the app fairly significantly and creating a lot of very difficult to maintain code. Perhaps if we link to the document management system this would provide a better user experience then what we currently have.

**Comment by harmeet-status** [comment]
Makes sense to wait till DMS implemented. Would not like this to open in the DMS, we are using it as a headless system.

I think we would only allow opening image files in another tab, otherwise you download it.

**Comment by harmeet-status** [comment]
Chatting to other at Athens, it seems that people don't even care about opening in a new tab (although that's nice). They would just prefer a modal overlay showing the file -- perhaps we can do this as part of the new UI designs.
