### ISSUE TITLE
Configure GitHub to Notify SpiffWorkflow when a PR is approved

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#955]
The [Bounty process](https://cawemo.com/share/29b8873a-8332-42ca-bd75-864bddea8bc4) needs to be notified by GitHub that the PR for a specific issue assigned by the process has been approved.

**Comment by harmeet-status** [comment]
Use Github actions.

**Comment by calexh-sar** [comment]
Combined with #820

**Comment by burnettk** [comment]
github actions or a github app may work, here. a github app may be required to implement the items on #820 anyway, since non-app oauth integrations do not fine-grained github api permissions, so using the standard github app interaction with webhooks might be preferable, but it's good to have options.
