### ISSUE TITLE
Shopify Integration with Iplicit via Spiff - Call to retrieve data

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#993]
Process in WIP - this is a placeholder until complete information is available
- need to retrieve order data from Shopify
- need to retrieve payment data from Shopify
- Shopify allows oauth
- need mapping of Shopify data to Iplicit data
- need a report of order and payment data
- Spiff acts as an integration and communication layer between Shopify and Iplicit
- data is sensitive and needs to be restricted in the process instance

**Comment by calexh-sar** [comment]
@MarD0607 is there a samdbox Shopify account we can use for this issue?  Is there a defined process model?

**Comment by calexh-sar** [comment]
@MarD0607 I am pretty sure REST is the option we prefer between those two, but asking @jbirddog just to be sure. 

Any update on getting the sandbox available?

**Comment by jbirddog** [comment]
https://shopify.dev/docs/api/admin/migrate

it looks like shopify is pushing people toward graphql instead of rest. i don't think it will really impact us much at all to use GraphQL but also don't think we have ever made a call with it vs traditional REST. GraphQL does have some nice features like being able to limit what fields are returned, combining multiple calls into one, etc. If for some reason the GraphQL call does not work as expected it we can tweak the http connector.
